package jp.kaleidot725.emomemo.view.pages.memo

data class MemoDetailState(
    val test: String =
        """
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
TEST TEST TEST
"""
)
