name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6' # Version range or exact version of a Ruby version to use, using semvers version range syntax.
    - name: install danger
      run: gem install danger
    - name: run ktlintCheck
      run: ./src/gradlew ktlintCheck
    - name: run danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: danger
