name: CI

on: pull_request

jobs:
  check:
    name: Check pull request    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: run ktlintCheck
      run: |
        cd src
        ./gradlew ktlint
    - name: run androidLint
      run: |
        cd src
        ./gradlew lint
    - name: run danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gem install danger
        danger 
