name: merge_check

on:
  push:
    branches:
      - master
      
jobs:
  check:
    name: Check pull request    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - name: run ktlintCheck
      run: |
        cd src
        ./gradlew --continue ktlintCheck
    - name: run androidLint
      run: |
        cd src
        ./gradlew lint
    - name: run test
      run: |
        cd src
        ./gradlew test
    - name: run danger
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gem install danger danger-checkstyle_format danger-android_lint danger-junit
        danger 
